### ISSUE TITLE
response says name and email not set after registration

### ISSUE THREAD

**Issue by chinazaaa** [hngi/sentry-my-customer-api#204]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):

**Expected behavior**
Name and email should show in the response

**Screenshots**
![image](https://user-images.githubusercontent.com/50022245/86222865-b5e24600-bb7e-11ea-9689-33b7d058a97d.png)

**Desktop (please complete the following information):**

**How do you intend to solve this bug?**
Describe in clear and concise manner how you intend to approach fixing this bug.

**Slack username**
Please include your slack username here

**Additional context**

**Comment by emasontech** [comment]
Give us screen shot of data sent to the api

**Comment by emasontech** [comment]
Am interested to work

**Comment by sandygudie** [comment]
Issue fixed... sending PR

**Comment by sandygudie** [comment]
**Describe the bug**
The names and email were not passed to the correctly req. body needed to save in the database.

Steps to reproduce the behavior (please point us to the relevant files):
Go to 'register.controller.js'
 Error from the "registerUser function

Desktop (please complete the following information):
Browser [e.g. chrome, safari]

The bug was fixed by passing the data from the req.body to the where it is save to the database.

**Slack username**
@Sandy

[PR LINK](https://github.com/hngi/sentry-my-customer-api/pull/213)

screenshot of successful response
[bug fixed](https://res.cloudinary.com/dvpoiwd0t/image/upload/v1593616389/bug_fixed_ji0g3y.jpg)

**Comment by chinazaaa** [comment]
Okay
